//enumeration des grands prix pour l'image dans le timeSlider
export const GrandPrix = {
  Australie: "data/grands-prix/melbourne.png",
  Austin: "data/grands-prix/austin.png",
  Bahrein: "data/grands-prix/bahrain.png",
  Baku: "data/grands-prix/baku.png",
  Espagne: "data/grands-prix/barcelone.png",
  Monaco: "data/grands-prix/monaco.png",
  Hongrie: "data/grands-prix/hungaroring.png",
  Imola: "data/grands-prix/imola.png",
  Brésil: "data/grands-prix/bresil.png",
  Jeddah: "data/grands-prix/jeddah.png",
  Singapour: "data/grands-prix/singapour.png",
  Miami: "data/grands-prix/miami.png",
  Monza: "data/grands-prix/monza.png",
  Autriche: "data/grands-prix/redBullRing.png",
  France: "data/grands-prix/castellet.png",
  Mexique: "data/grands-prix/mexique.png",
  Silverstone: "data/grands-prix/silverstone.png",
  Belgique: "data/grands-prix/spaFrancorchamps.png",
  Japon: "data/grands-prix/suzuka.png",
  Canada: "data/grands-prix/canada.png",
  "Abu Dhabi": "data/grands-prix/abuDhabi.png",
  Zandvoort: "data/grands-prix/zandvoort.png",
};

//énumeration des noms des pilotes selon leur abréviation
export const Pilote = {
  VET: "Vettel",
  BOT: "Bottas",
  GAS: "Gasly",
  PER: "Perez",
  HAM: "Hamilton",
  RIC: "Ricciardo",
  OCO: "Ocon",
  ALB: "Albon",
  MAG: "Magnussen",
  VER: "Verstappen",
  ALO: "Alonso",
  LEC: "Leclerc",
  SAI: "Sainz",
  ZHO: "Zhou",
  RUS: "Russell",
  LAT: "Latifi",
  SCH: "Schumacher",
  NOR: "Norris",
  TSU: "Tsunoda",
  STR: "Stroll",
};

//énumeration des couleurs des pilotes selon leur abréviation
export const CouleurPilote = {
  VET: "#006F62",
  BOT: "#900000",
  GAS: "#2B4562",
  PER: "#0600EF",
  HAM: "#00D2BE",
  RIC: "#FF8700",
  OCO: "#0090FF",
  ALB: "#005AFF",
  MAG: "#FFFFFF",
  VER: "#0600EF",
  ALO: "#0090FF",
  LEC: "#DC0000",
  SAI: "#DC0000",
  ZHO: "#900000",
  RUS: "#00D2BE",
  LAT: "#005AFF",
  SCH: "#FFFFFF",
  NOR: "#FF8700",
  TSU: "#2B4562",
  STR: "#006F62",
};
